service: crud-serverless-user

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:us-east-1:146911859667:table/usersTable

plugins:
  - serverless-dynamodb
  - serverless-offline
 
package:
  individually: true
  patterns:
    - "!.dynamodb"
    - "!.node_modules"

custom:
  serverless-dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions:
  get-users:
    handler: getusers/handler.getUsers
    events:
      - http:
          path: users/{id}
          method: GET
  create-users:
    handler: createusers/handler.createUsers
    events:
      - http:
          path: users
          method: POST
  update-users:
    handler: updateusers/handler.updateUsers
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-users:
    handler: deleteusers/handler.deleteUsers
    events:
      - http:
          path: users/{id}
          method: DELETE

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

